services:
  postgres:
    image: postgres:16
    container_name: smart-expense-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_expense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - smart_expense_data:/var/lib/postgresql/data
volumes:
  smart_expense_data: